### ISSUE TITLE
Swipe up and Hold is also executing Swipe Up gesture. Holding for longer keeps repeating gesture.

### ISSUE THREAD

**Issue by sangeet** [zacharee/nobar-issues#118] opened 2019-07-07 20:52 UTC
**Describe the bug**
Hi, I just updated this app version today and it broke the gesture setup that I have been using for about forever now. Let me explain :

I use XDA Navigation Gestures in Split Pill mode and here are the actions that I have assigned to the pills :
Swipe Up from Right : Quick Settings (Premium)
Swipe Up and Hold from Right (Back)

Problem :
I am mentioning only these are they are the ones that I have issues with. The problem I have is that when I go back i.e Swipe Up and Hold from Right, then sometimes after the back gesture is executed (and I leave the touch, mouseout?), it also executes the Swipe Up from Right gestures (i.e Quick Settings in my case) too.
Hence, instead of simply going back, I go back (gesture 1) and my quick settings open up (gesture 2), so one gesture is executing an unintended second gesture. This was not the case in the previous version that I was using before Update. I manually update version hence I haven't kept track of the previous version, but it wouldn't have been very long.
Also if I continue holding the screen after the gesture has been executed for a second or two then it just keeps taking me back after a specific delay between each screen (go 4-5 levels deep in settings and continue holding after swiping up from right and hold), i.e keeps repeating the back gesture even when I haven't even lifted my finger up. This is always reproducible.

Note that the first problem (quick settings along with back) only happens when the screen changes (I believe activity is the correct technical term maybe). So this only happens when I am going back in settings screens, moving from whatsapp chat page to home page, etc and then too it sometimes works flawlessly while gives issues otherwise with the same app under same gesture (settings, whatsapp). This is not a problem when moving between the Navigation Gesture screens app itself or when pressing the back button in say a web browser which doesn't change the screen. 100% reproducible with Settings and WhatsApp.

**To Reproduce**

Apply the following settings :

Split Pill enabled
Swipe Up from Right : Quick Settings (Premium)
Swipe Up and Hold from Right : Back
Swipe and Hold Time : 150ms (Durations)
Vertical (Y) Up-Swipe Diatance : 4 dp (Sensitivity)

Go to WhatsApp and go a level or two deep, then swipe up right and hold and after delay period release. It should open the Quick settings option, that is execute Swipe Up gesture too. Try again if it didn't happen. It happens at random.

Then try and same in settings. Go 4-5 levels deep and swipe up and hold but don't release, it will keep pushing back after a delay of a second or so automatically.

**Expected behavior**
The swipe up and hold gesture is supposed to just execute that gesture once and stop executing further gestures as was the case earlier and it worked flawlessly before update.

**Screenshots/Recordings**
If applicable, add screenshots or recordings to help explain your problem.

**Smartphone (please complete the following information):**
 - Navigation Gestures version: 1.15.4 Updated On: 08-Jun-2019
 - Device: Asus Zenfone Max Pro M1
 - Android Version : 8.1.0 (Lineage OS ROM)
 - LineageOS Version : 15.1.29190213-NIGHTLY-X00TD
 - Kernel Version : 4.4.138-perf+

**Additional context**

**Comment by zacharee** [comment] 2019-07-19 18:58
I'm unable to reproduce this on 1.15.6.

**Comment by marnovo** [comment] 2019-07-30 11:19
Very similar here on 1.15.7, Galaxy S9+, Android 9, Samsung OneUI 1.0, kernel 4.9.59.

Seems like gestures are either overlapping or going one after each other (very clear if you swipe a certain way and keep holding it indefinitely, you get each non stop).

**Comment by sangeet** [comment] 2019-07-31 09:39
I have given up on this application and have switched to another application, therefore I am not concerned with this bug anymore.

Seems like @marnovo has a similar problem, so let's keep the thread open for him. Feel free to close this out if required.

**Comment by zacharee** [comment] 2019-08-21 20:57
This should be fixed in 1.15.10.

**Closed as completed** 2019-09-15 15:01 UTC
